### ISSUE TITLE
Add `pyproject.toml` for pip 

### ISSUE THREAD

**Issue by hoosnick** [PayTechUz/payme-pkg#5]
https://github.com/pypa/pip/issues/8559

1. A package failing to build. Scroll up in the output to see if "Building wheel" failed for the same package. If yes, then you want to investigate that issue and not this warning.

2. Or, `wheel` not being installed in your environment.
If you're a user, install that package in the environment to avoid hitting this issue.
If you're the package author, make sure you can install the package with `--use-pep517` passed into pip.

**Comment by Muhammadali-Akbarov** [comment]
fixed on version 3+
