### ISSUE TITLE
AccessDeniedError.__init__() got an unexpected keyword argument 'message'

### ISSUE THREAD

**Issue by ChogirmaliYigit** [PayTechUz/payme-pkg#95]
![image](https://github.com/user-attachments/assets/472d4b6a-3fdd-4c41-a378-66d47a357340)

Here's my code snippet that gave me the error
```python
from django.conf import settings

from payme import Payme


payme_client = Payme(
    payme_id=settings.PAYME_ID,
    payme_key=settings.PAYME_KEY,
    is_test_mode=True,
)


payme_response = payme_client.cards.check("<my_token>")
```

The reason is the `PAYME_ID` and `PAYME_KEY` variables are both `None`. So Payme Subscribe API returned Access Denied error and the package had tried to raise the exception with `payme.exceptions.general.AccessDeniedError` class.

The error occurred in the `payme.classes.http.HttpClient.handle_payme_error` method. There the package tries to get the exception class by error code:

```python
def handle_payme_error(self, error: dict):
    """
    Handle Paycom-specific errors from the JSON-RPC error response.

    Parameters
    ----------
    error : dict
        The error dictionary from Paycom's response, typically containing
        error details such as code, message, and data.

    Returns
    -------
    None
        Raises an exception based on the error code received from
        Paycom's response.
    """
    error_code = error.get("code", "Unknown code")
    error_message = error.get("message", "Unknown error")
    error_data = error.get("data", "")

    exception_class = exc.errors_map.get(error_code, exc.BaseError)
    raise exception_class(message=error_message, data=error_data)

```

The main problem is the `handle_payme_error` method tries to get exception class and pass `message` and `data` arguments. But there are no such arguments in the `__init__` methods of some classes (`AccessDeniedError`, `InvalidParamsError`, `CardNotFoundError`, etc.).

**Comment by Muhammadali-Akbarov** [comment]
![image](https://github.com/user-attachments/assets/f0752d88-1239-421f-94b3-7d3fa035728c)

Thanks for reporting, it was small issue and now it's working without issues
